services:
  - type: web
    name: flask-chat
    env: python
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: SECRET_KEY
        value: "0012"  
      - key: EVENTLET_NO_GREENDNS
        value: "1"
    startCommand: "gunicorn -k eventlet -w 1 app:app"
