services:
  - type: web
    name: flask-chat
    env: python
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: SECRET_KEY
        value: "your-automatically-generated-secret-key"  # Replace with a secure value or generator
    startCommand: "gunicorn -k eventlet -w 1 app:app"
